### ISSUE TITLE
Travelers-Hub: Set-up Kanban Board

### ISSUE THREAD

**Issue by ZikaZaki** [ZikaZaki/travelers-hub#25]
# Travelers-Hub: Set-up Kanban Board

### Here's the link to our [Kanban Board](https://github.com/ZikaZaki/travelers-hub/projects/1).
-----
### **:exclamation:Important:** I am the only contributor to this project **(working-solo)**, and that because my block appeal got approved too late.
- **👤 [Zakariya Al-Khamisi](https://github.com/ZikaZaki/).**

**Comment by DammyShittu** [comment]
Hi @ZikaZaki,

## APPROVED 🟢

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
